---

# The idea is based on the special variables ansible_play_batch and ansible_play_hosts_all
#
#   * ansible_play_hosts_all: List of all the hosts that were targeted by the play
#
#   * ansible_play_batch: List of active hosts in the current play run limited by the serial, 
#     aka ‘batch’. Failed/Unreachable hosts are not considered ‘active’.
#
#  So this script must be run when:
#           "ansible_play_batch | length != ansible_play_hosts_all | length"
#  And it happens when any task has failed in any host, so the role run must be stopped to 
#  avoid problems in the read-only site. This file includes tasks to start services stopped when 
#  running the replicastion script

#Add more tasks to restart nginx, php-fpm or workers stopped when starting the replication script

- shell: /bin/false
  when: "ansible_play_batch | length != ansible_play_hosts_all | length"
  throttle: 1
