---

- name: "Import edit user and clipboard_save_item tables from backup"
  become: "yes"
  mysql_db:
    name: "{{ atom_replication_ro_db_name }}"
    state: "import"
    target: "{{ atom_replication_ro_mysql_snapshots_dir }}/mysql_ro_table_clipboard_save_item.sql"

- name: "read user snapshot as CSV"
  read_csv:
    path: "{{ atom_replication_ro_mysql_snapshots_dir }}/mysql_ro_table_user.tsv"
    delimiter: "\t"
  register: __users_from_tsv

- name: "Restore user credentials"
  become: "yes"
  mysql_query:
    login_db: "{{ atom_replication_ro_db_name }}"
    login_unix_socket: "{{ atom_replication_ro_mysql_unix_socket }}"
    query:
      - UPDATE user SET password_hash=%s, salt=%s, active=%s WHERE email=%s
    positional_args:
      - '{{ item.password_hash }}'
      - "{{ item.salt }}"
      - "{{ item.active|int }}"
      - "{{ item.email }}"
  with_items: "{{ __users_from_tsv.list }}"
  loop_control:
    label: "Restoring credentials for {{ item.email }}"

- name: "Delete contents in clipboard_save table"
  become: "yes"
  mysql_query:
    login_db: "{{ atom_replication_ro_db_name }}"
    login_unix_socket: "{{ atom_replication_ro_mysql_unix_socket }}"
    query:
      - DELETE FROM clipboard_save

- name: "read clipboard_save snapshot as TSV"
  read_csv:
    path: "{{ atom_replication_ro_mysql_snapshots_dir }}/mysql_ro_table_clipboard_save.tsv"
    delimiter: "\t"
  register: __clipboard_save_from_tsv

- name: "Restore clipboard_save table entries"
  become: "yes"
  mysql_query:
    login_db: "{{ atom_replication_ro_db_name }}"
    login_unix_socket: "{{ atom_replication_ro_mysql_unix_socket }}"
    query:
      - INSERT INTO clipboard_save(id, user_id, password, created_at) VALUES (%s, (SELECT id FROM user WHERE email=%s' LIMIT 1),%s,%s)
    positional_args:
      - "{{ item.id|int }}"
      - "{{ item.email }}"
      - "{{ item.password }}"
      - "{{ item.created_at }}"
  with_items: "{{ __clipboard_save_from_tsv.list }}"
  loop_control:
    label: "Restoring clipboard {{ item.password }} created by {{ item.email }} @ {{ item.created_at }}"
