---

- name: "Get siteBaseUrl id from setting and setting_i18n"
  become: "yes"
  mysql_query:
    login_db: "{{ atom_replication_ro_db_name }}"
    query:
      - SELECT s.id FROM setting s INNER JOIN setting_i18n si ON s.id=si.id AND s.name='siteBaseUrl'
  register: __siteBaseUrl_id

- name: "Use read-only base URL"
  become: "yes"
  mysql_query:
    login_db: "{{ atom_replication_ro_db_name }}"
    query:
      - UPDATE setting_i18n SET value='{{ atom_replication_ro_dnsname }}' WHERE id=%s AND culture='en'
    positional_args:
      - "{{ __siteBaseUrl_id.query_result[0][0].id }}"


- name: "Update urls for cached xml files"
  become: "true"
  shell: |
    find "{{ atom_replication_ro_path  }}" -type f -iname '*.xml' -exec sed -i "s/{{ atom_replication_edit_dnsname }}/{{ atom_replication_edit_dnsname }}/g" {} \;

