---

- name: "Delete ES backup repo directory on ES edit server"
  file:
    path: "{{ atom_replication_es_backup_repo_path }}"
    state: "absent"

- name: "Create ES backup repo directory on ES edit server"
  file:
    path: "{{ atom_replication_es_backup_repo_path }}"
    state: "directory"
    mode: "0775"
    owner: "{{ atom_replication_snapshot_es_user }}"
    group: "{{ atom_replication_snapshot_es_group }}"

- name: "Take atom index snapshot on ES edit server - Single index"
  uri:
    url: "{{ atom_replication_edit_es_base_url }}:{{ atom_replication_es_port }}/_snapshot/{{ atom_replication_es_repo_name }}/{{ atom_replication_es_snapshot_name }}?wait_for_completion=true"
    method: "PUT"
    body:
      indices: "{{ atom_replication_edit_es_index }}"
      ignore_unavailable: "true"
    body_format: "json"
    timeout: 600
    use_proxy: false
  when:
    - not atom_replication_es_multiple_indices|bool

- name: "Take atom index snapshot on ES edit server - Multiple indices"
  uri:
    url: "{{ atom_replication_edit_es_base_url }}:{{ atom_replication_es_port }}/_snapshot/{{ atom_replication_es_repo_name }}/{{ atom_replication_es_snapshot_name }}?wait_for_completion=true"
    method: "PUT"
    body:
      indices: "{{ __indices_string_edit }}"
      ignore_unavailable: "true"
    body_format: "json"
    timeout: 600
    use_proxy: false
  when:
    - atom_replication_es_multiple_indices|bool

- name: "create tarball of the ES repo"
  archive:
    path: "{{ atom_replication_es_backup_repo_path }}/"
    dest: "{{ atom_replication_edit_es_snapshots_dir }}/es-snapshot.tgz"
    owner: "{{ ansible_ssh_user }}"
    mode: "0640"

- name: "Copy ES backup to ansible host (with synchronize)"
  synchronize:
    mode: pull
    src: "{{ atom_replication_edit_es_snapshots_dir }}/es-snapshot.tgz"
    dest: "{{ atom_replication_ansible_host_snapshots_dir }}/es-snapshot.tgz"
  become: no
