---

- name: "Delete ES backup repo directory on ES edit server"
  file:
    path: "{{ atom_replication_es_backup_repo_path }}"
    state: "absent"

- name: "Create ES backup repo directory on ES edit server"
  file:
    path: "{{ atom_replication_es_backup_repo_path }}"
    state: "directory"
    mode: "0775"
    owner: "{{ atom_replication_snapshot_es_user }}"
    group: "{{ atom_replication_snapshot_es_group }}"

- name: "Take atom index snapshot on ES edit server"
  uri:
    url: "http://127.0.0.1:{{ atom_replication_es_port }}/_snapshot/{{ atom_replication_es_repo_name }}/{{ atom_replication_es_snapshot_name }}?wait_for_completion=true"
    method: "PUT"
    body:
      indices: "{{ atom_replication_edit_es_index }}"
      ignore_unavailable: "true"
    body_format: "json"
    timeout: 600

- name: "create tarball of the ES repo"
  archive:
    path: "{{ atom_replication_es_backup_repo_path }}/"
    dest: "{{ atom_replication_edit_es_snapshots_dir }}/es-snapshot.tgz"

- name: "Fetch ES backup on ansible host"
  fetch:
    src: "{{ atom_replication_edit_es_snapshots_dir }}/es-snapshot.tgz"
    dest: "{{ atom_replication_ansible_host_snapshots_dir }}/es-snapshot.tgz"
    flat: "true"
  no_log: true
