---


- name: "Install PyMySQL package on MySQL edit host"
  become: "yes"
  package:
    name: "{{ atom_replication_pymysql_package }}"
    state: "present"

- name: "Create source mysqldump on MySQL edit host"
  become: "yes"
  mysql_db:
    name: "{{ atom_replication_edit_db_name }}"
    single_transaction: "yes"
    # Appending database name to the atom_replication_ro_backup_tables list
    ignore_tables: "{{ [atom_replication_edit_db_name] | product(atom_replication_ro_backup_tables) | map('join','.') | list }}"
    dump_extra_args: "--add-drop-table --skip-dump-date"
    state: "dump"
    target: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"

- name: "Fetch MySQL backup on ansible host"
  fetch:
    src: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
    dest: "{{ atom_replication_ansible_host_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
    flat: "true"
  no_log: true

- name: "Take user table backup on MySQL edit server when synchronizing clipboards and users"
  block:
    - name: "Dump user table"
      become: "yes"
      mysql_db:
        name: "{{ atom_replication_edit_db_name }}"
        single_transaction: "yes"
        dump_extra_args: "--add-drop-table --skip-dump-date --tables user"
        state: "dump"
        target: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql_ro_table-user.sql.gz"

    - name: "Fetch MySQL user table backup on ansible host"
      fetch:
        src: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql_ro_table-user.sql.gz"
        dest: "{{ atom_replication_ansible_host_snapshots_dir }}/mysql_ro_table-user.sql.gz"
        flat: "true"
      no_log: true
  when:
    - atom_replication_synchronize_clipboard|bool
  #End block
