---

- name: "Create source mysqldump on MySQL edit host"
  become: "yes"
  mysql_db:
    name: "{{ atom_replication_edit_db_name }}"
    login_unix_socket: "{{ atom_replication_edit_mysql_unix_socket }}"
    single_transaction: "yes"
    # Appending database name to the atom_replication_ro_backup_tables list
    ignore_tables: "{{ [atom_replication_edit_db_name] | product(atom_replication_ro_backup_tables) | map('join','.') | list }}"
    dump_extra_args: "--add-drop-table --skip-dump-date"
    state: "dump"
    target: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"

- name: "Fix owner/perms of mysql dump tarball"
  file:
    path: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
    owner: "{{ atom_replication_edit_atom_ansible_user }}"
    mode: "0664"
  become: yes

- name: "Copy MySQL backup to Ansible host (with synchronize)"
  synchronize:
    mode: "pull"
    src: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
    dest: "{{ atom_replication_ansible_host_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
  become: no

- name: "Take user table backup on MySQL edit server when synchronizing clipboards and users"
  block:
    - name: "Dump user table"
      become: "yes"
      mysql_db:
        name: "{{ atom_replication_edit_db_name }}"
        login_unix_socket: "{{ atom_replication_edit_mysql_unix_socket }}"
        single_transaction: "yes"
        dump_extra_args: "--add-drop-table --skip-dump-date --tables user"
        state: "dump"
        target: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql_ro_table-user.sql.gz"

    - name: "Fix owner/perms of user table mysql dump tarball"
      file:
        path: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql_ro_table-user.sql.gz"
        owner: "{{ atom_replication_edit_atom_ansible_user }}"
        mode: "0664"
      become: yes

    - name: "Copy MySQL user table backup to Ansible host (with synchronize)"
      synchronize:
        mode: "pull"
        src: "{{ atom_replication_edit_mysql_snapshots_dir }}/mysql_ro_table-user.sql.gz"
        dest: "{{ atom_replication_ansible_host_snapshots_dir }}/mysql_ro_table-user.sql.gz"
      become: no

  when:
    - atom_replication_synchronize_clipboard|bool
  #End block
