---

- name: "Copy MySQL edit backup from ansible host to MySQL read-only host"
  copy:
    src: "{{ atom_replication_ansible_host_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
    dest: "{{ atom_replication_ro_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"
    owner: "{{ atom_replication_snapshot_mysql_user }}"
    group: "{{ atom_replication_snapshot_mysql_group }}"

- name: "Import edit database from backup"
  become: "yes"
  mysql_db:
    name: "{{ atom_replication_ro_db_name }}"
    login_unix_socket: "{{ atom_replication_ro_mysql_unix_socket }}"
    state: "import"
    target: "{{ atom_replication_ro_mysql_snapshots_dir }}/mysql-edit-snapshot.sql.gz"

- name: "Import read-only tables previously saved"
  become: "yes"
  mysql_db:
    name: "{{ atom_replication_ro_db_name }}"
    login_unix_socket: "{{ atom_replication_ro_mysql_unix_socket }}"
    state: "import"
    target: "{{ atom_replication_ro_mysql_snapshots_dir }}/mysql_ro_table_{{ item }}.sql"
  loop: "{{ atom_replication_ro_backup_tables }}"

