---
# handlers file for atom-replication-role

  - name: "restart elasticsearch"
    service:
      name: "elasticsearch"
      state: "restarted"
    listen: "elasticsearch"

  - name: "restart nginx"
    service:
      name: "nginx"
      state: "restarted"
    listen: "nginx"

  - name: "send notification email"
    mail:
      host: "{{ atom_replication_email_notification_host | default('localhost') }}"
      port: "{{ atom_replication_email_notification_port | int | default(25) }}"
      to: "{{ atom_replication_email_notification_to }}"
      cc: "{{ atom_replication_email_notification_cc | default(omit) }}"
      attach: "{{ ansible_env.ANSIBLE_LOG_PATH }}"
      subject: "{{ _playbook_status }}: {{ atom_replication_email_notification_subject }}"
      body: "{{ atom_replication_email_notification_body | default(omit) }}"
      secure: "{{ atom_replication_email_notification_secure | default(omit) }}"
      sender: "{{ atom_replication_email_notification_sender | default(omit) }}"
      subtype: "{{ atom_replication_email_notification_subtype | default('plain') }}"
      username: "{{ atom_replication_email_notification_username | default(omit) }}"
      password: "{{ atom_replication_email_notification_password | default(omit) }}"
    listen: "email_notification"
