---
- hosts: localhost
  vars:
    atom_replication_config: "config.yml"
  vars_files:
    - "{{ atom_replication_config }}"

- hosts:
    - "{{ atom_replication_ansible_remote_server }}"
    - "{{ atom_replication_edit_atom_host }}"
    - "{{ atom_replication_ro_atom_host }}"
    - "{{ atom_replication_edit_es_host }}"
    - "{{ atom_replication_ro_es_host }}"
    - "{{ atom_replication_edit_mysql_host }}"
    - "{{ atom_replication_ro_mysql_host }}"
  vars:
    atom_replication_config: "config.yml"
  vars_files:
    - "{{ atom_replication_config }}"

  roles:

    - role: "artefactual.atom-replication"
      become: "yes"
      tags:
        - "atom-replication"
